version: '3.9'
services:
  main:
    build:
      context: ./ingredients
      args:
        AWS_DEFAULT_REGION: ap-northeast-2
        AWS_ACCESS_KEY_ID: 
        AWS_SECRET_ACCESS_KEY: 
    volumes:
      - type: bind
        source: ./ingredients/work
        target: /root/server/work
      # - flask_volume: /root/server/work
    ports:
    - "5000:5000"
  recipe:
    build:
      context: ./recipe
      args:
        AWS_DEFAULT_REGION: ap-northeast-2
        AWS_ACCESS_KEY_ID: 
        AWS_SECRET_ACCESS_KEY:  
    volumes:
      - type: bind
        source: ./recipe/work
        target: /root/server/work
    ports:
    - "5001:5001"
  user:
    build:
      context: ./user
      args:
        AWS_DEFAULT_REGION: ap-northeast-2
        AWS_ACCESS_KEY_ID: 
        AWS_SECRET_ACCESS_KEY:  
    volumes:
      - type: bind
        source: ./user/work
        target: /root/server/work
    ports:
    - "5002:5002"
volumes:
    flask_volume:

